[package]
name = "ropr"
version = "0.2.23"
authors = ["Ben Lichtman"]
edition = "2021"
description = "A blazing fast multithreaded ROP Gadget finder. ropper / ropgadget alternative"
repository = "https://github.com/Ben-Lichtman/ropr"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "1.0.37"
goblin = "0.5.4"
iced-x86 = "1.17.0"
colored = "2.0.0"
regex = "1.6.0"
rayon = "1.5.3"
clap = { version = "4.0.7", features = ["derive"] }
