[package]
name = "ropr"
version = "0.1.0"
authors = ["Ben Lichtman"]
edition = "2018"
description = "A multithreaded ROP Gadget finder. ropper / ropgadget alternative inspired by xgadget"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "1.0.20"
goblin = "0.2.3"
zydis = "3.1.1"
colored = "1.9.3"
rayon = "1.3.1"
structopt = "0.3.15"
