[package]
name = "ropr"
version = "0.2.1"
authors = ["Ben Lichtman"]
edition = "2018"
description = "A blazing fast multithreaded ROP Gadget finder. ropper / ropgadget alternative"
repository = "https://github.com/Ben-Lichtman/ropr"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "1.0.20"
goblin = "0.2.3"
iced-x86 = "1.10.0"
colored = "2.0.0"
structopt = "0.3.17"
regex = "1.3.9"
rayon = "1.5.0"
